modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/Namefix/deadeye/issues"
license = "GPL-3.0"

[[mods]]
modId = "deadeye"
version = "${version}"
displayName = "Dead Eye"
authors = "Namefix"
description = '''
A mod that implements Dead Eye Targeting from the Red Dead Redemption series.
'''
logoFile = "assets/deadeye/icon.png"

[[dependencies.deadeye]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.deadeye]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.deadeye]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.deadeye]]
modId = "resourcefulconfig"
mandotory = true
versionRange = "[2.1.3,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "deadeye.mixins.json"

[[mixins]]
config = "deadeye.forge.integrations.mixins.json"
